### ISSUE TITLE
question: parse_cfg: [net] 'subdivisions' is not supported

### ISSUE THREAD

**Issue by junmcenroe** [PROGrand/yolo-coreml#1]
Dear Author

I just tried your converter after download the coco.names, darknet.weights, darknet.cfg from darknet
and run
$convert_v4.py -n coco.names -c darknet.cfg -w yolov4.weights -m sample.mlpackage
but following  error happened.
*****
ARNING:root:TensorFlow version 2.7.0 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.5.0 is the most recent version that has been tested.
WARNING:root:Keras version 2.7.0 has not been tested with coremltools. You may run into unexpected errors. Keras 2.2.4 is the most recent version that has been tested.
Call tf.config.experimental.set_memory_growth(GPU0, True)
names:  coco.names
config:  darknet.cfg
weights:  yolov4.weights
mlpackage:  coco.names
Traceback (most recent call last):
  File "/Users/***/miniforge3/envs/tensorflow25/lib/python3.8/site-packages/yolov4/common/parser.py", line 101, in parse_cfg
    metalayers[layer.name][option] = value
  File "/Users/***/miniforge3/envs/tensorflow25/lib/python3.8/site-packages/yolov4/common/metalayer/net_layer.py", line 146, in __setitem__
    raise KeyError(f"'{key}' is not supported")
KeyError: "'subdivisions' is not supported"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../convert_v4.py", line 64, in <module>
    _main(parser.parse_args())
  File "../convert_v4.py", line 39, in _main
    yolo.config.parse_cfg(config_path)
  File "/Users/***/miniforge3/envs/tensorflow25/lib/python3.8/site-packages/yolov4/common/config.py", line 69, in parse_cfg
    ) = parser.parse_cfg(cfg_path=cfg_path)
  File "/Users/***/miniforge3/envs/tensorflow25/lib/python3.8/site-packages/yolov4/common/parser.py", line 103, in parse_cfg
    raise RuntimeError(
RuntimeError: parse_cfg: [net] 'subdivisions' is not supported.

****
my environment is
macOS Monterey 12.0.1
python 3.8.12
coremltools             5.1.0
keras                   2.7.0
tensorflow-macos        2.7.0
tensorflow-metal        0.3.0
yolov4                  3.2.0

I am beginner of this area, so I think I made fundamental mistake. 
if you can advice, it is very pleasure for me.

**Comment by PROGrand** [comment]
Hello, you missed one step - _`preparation of config`_, it cleans learning tag like `subdivisions`:
```
sh ./prepare_cfg.sh darknet.cfg darknet_t.cfg
```

then use `darknet_t.cfg` instead of `darknet.cfg`:
```
convert_v4.py -n coco.names -c darknet_t.cfg -w yolov4.weights -m sample.mlpackage
```

**Comment by PROGrand** [comment]
Also i can see your python, keras and tensorflow are of newer versions. It is unsupported setup, because coremltools is very sensitive to packages versions. This is why you need dedicated python anaconda environment. Anaconda gives your the ability to have different python environments on one computer.

**Comment by junmcenroe** [comment]
Dear Author

Thanks for your quick response. I tried after preparation as you pointed out.
The result was to appear the following error
KeyError: "'max_crop' is not supported"
then I removed "max_crop" from cfg, and tried and found another error
KeyError: "'padding' is not supported"
after removing the "padding", following error came out
KeyError: 'avgpool'

cannot make it at all.
My MacBook Air is M1 , and I built the virtual environment with miniforge3(mini CONDA), and TensorFlow is for M1 Mac because other TF version cannot install to my MacBookAir.

No way to solve my issue?

**Comment by PROGrand** [comment]
Can you provide links to you cfg and weights?
PS: Converting of networks can be performed on virtual pc like Amazon EC2 free-teer instances. It is important to have exact versions of TF.

**Comment by junmcenroe** [comment]
Dear Author

I gave up on my M1 Mac, but I tried on Windows10.
At first, I tried with YOLOv4-Mish with following command after installed in accordance with your guide.
>python convert_v4_old.py yolov4.cfg yolov4.weights yolov4.mlmodel

I got the mlmodel(python version was key), and can imported this model to Xcode, and I can see the 3 anchors output such as 
output3: MultiArray(Float32 255x64x64)  description :the 52x52 grid
output2:MultiArray(Float32 255x32x32)  description :the 26x26 grid
output1:MultiArray(Float32 255x16x16) description: the 13x13 grid
This old version conveter's out put is MultiArray. Is it correct? If I detect object on Xcode, I need to add the head with pipeline of coremltools. Am I right?
It is very tough work for me. I will try  new converter again on Windows10, but I think coremltools 5.1 do not support Windows.

**Comment by PROGrand** [comment]
Outputs of mlmodels of this project are MLMultiArray. These are [yolo] layers coefficients. ios examples uses code to interpret [yolo] as prediction boxes. Modern example requires only anchors modifications for your model. Oldest one requires little bit more work.

I used Ubuntu and anaconda3 via WSL2 on Windows 10/11 without any troubles.

**Comment by junmcenroe** [comment]
Dear Author

I found your ios project. Copy yolov4.mlmodel to project folder, and completed and can transfer on my iPhone or iPad. 
But I encountered following error in Xcode debug area.
*****
yolov4[12923:4317659] fopen failed for data file: errno = 2 (No such file or directory)
yolov4[12923:4317659] Errors found! Invalidating cache...
*****
So I cannot open this sample app in my iPhone.
I do not know which file is missed. I put yolov4.mlmodel file is drag & drop in project and complied.

If you have a time, could you advise me?

Additionally, I run the simulator mode, and fond the following error msg
****
>[coreml] A Core ML custom neural network layer requires an implementation named 'Mish' which was not found in the global namespace.
> [coreml] Error creating Core ML custom layer implementation from factory for layer "Mish".
>yolov4[3418:80724] [espresso] [Espresso::handle_ex_plan] exception=Failed in 2nd reshape after missing custom layer info.
>yolov4[3418:80724] [coreml] Error in adding network -1.
>yolov4[3418:80724] [coreml] MLModelAsset: load failed with error Error Domain=com.apple.CoreML Code=0 "Error in declaring network." UserInfo={NSLocalizedDescription=Error in declaring network.}
>yolov4[3418:80724] [coreml] MLModelAsset: modelWithError: load failed with error Error Domain=com.apple.CoreML Code=0 "Error in declaring network." UserInfo={NSLocalizedDescription=Error in declaring network.}
Error Domain=com.apple.CoreML Code=0 "Error in declaring network." UserInfo={NSLocalizedDescription=Error in declaring network.}
*******
Above error msg, probably I need to add the MISH define in Swift code. But I can't  do that.

**Comment by PROGrand** [comment]
ios folder contains project for mlpackage (coremltools 5.1)

Mish.swift stuff is part of ios_old project.

**Comment by junmcenroe** [comment]
Thanks for you advice. I will try mlpackage(coremltools5.1) later after setup completed on the environment on WSL2 on Windows 10.
BTW, I found the MISH resource on following repo. probably need some mod to apply to your repo. 
<script src="https://gist.github.com/TakaoNarikawa/cde26544babaab52ecb70b0f39d29979.js"></script>
